"""empty message

Revision ID: 8508fb5e8e3f
Revises: 
Create Date: 2020-03-04 13:00:51.989504

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8508fb5e8e3f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('guest_users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('guest_name', sa.String(length=60), nullable=True),
    sa.Column('guest_state', sa.String(length=60), nullable=True),
    sa.Column('is_admin', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_guest_users_guest_name'), 'guest_users', ['guest_name'], unique=True)
    op.create_index(op.f('ix_guest_users_guest_state'), 'guest_users', ['guest_state'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_guest_users_guest_state'), table_name='guest_users')
    op.drop_index(op.f('ix_guest_users_guest_name'), table_name='guest_users')
    op.drop_table('guest_users')
    # ### end Alembic commands ###
